export const UPDATE_CURRENT_COMPONENT = "UPDATE_CURRENT_COMPONENT"

export const FETCH_DOCTOR_SERVICES = "FETCH_DOCTOR_SERVICES"
export const FETCH_DOCTOR_SERVICES_SUCCESS = "FETCH_DOCTOR_SERVICES_SUCCESS"
export const FETCH_DOCTOR_SERVICES_ERROR = "FETCH_DOCTOR_SERVICES_ERROR"

