export const UPDATE_CURRENT_COMPONENT = "UPDATE_CURRENT_COMPONENT"

export const FETCH_DOCTOR_SERVICES = "FETCH_DOCTOR_SERVICES"
export const FETCH_DOCTOR_SERVICES_SUCCESS = "FETCH_DOCTOR_SERVICES_SUCCESS"
export const FETCH_DOCTOR_SERVICES_ERROR = "FETCH_DOCTOR_SERVICES_ERROR"

export const ADD_DOCTOR_SERVICE = "ADD_DOCTOR_SERVICE"
export const ADD_DOCTOR_SERVICE_SUCCESS = "ADD_DOCTOR_SERVICE_SUCCESS"
export const ADD_DOCTOR_SERVICE_ERROR = "ADD_DOCTOR_SERVICE_ERROR"

export const PUT_FOCUS_SERVICE = "PUT_FOCUS_SERVICE"
export const PUT_FOCUS_SERVICE_SUCCESS = "PUT_FOCUS_SERVICE_SUCCESS"

export const UPDATE_DOCTOR_SERVICE = "UPDATE_DOCTOR_SERVICE"
export const UPDATE_DOCTOR_SERVICE_SUCCESS = "UPDATE_DOCTOR_SERVICE_SUCCESS"
export const UPDATE_DOCTOR_SERVICE_ERROR = "UPDATE_DOCTOR_SERVICE_ERROR"

export const DELETE_DOCTOR_SERVICE = "DELETE_DOCTOR_SERVICE"
export const DELETE_DOCTOR_SERVICE_SUCCESS = "DELETE_DOCTOR_SERVICE_SUCCESS"
export const DELETE_DOCTOR_SERVICE_ERROR = "DELETE_DOCTOR_SERVICE_ERROR"

export const FETCH_CONSULTATIONS = "FETCH_CONSULTATIONS"
export const FETCH_CONSULTATIONS_SUCCESS = "FETCH_CONSULTATIONS_SUCCESS"
export const FETCH_CONSULTATIONS_ERROR = "FETCH_CONSULTATIONS_ERROR"

export const PUT_FOCUS_CONSULTATIONS = "PUT_FOCUS_CONSULTATIONS"
export const PUT_FOCUS_CONSULTATIONS_SUCCESS = "PUT_FOCUS_CONSULTATIONS_SUCCESS"